### ISSUE TITLE
figure out why pinpad gets rid of buttons on main page

### ISSUE THREAD

**Issue by tyler-markvluwer** [tyler-markvluwer/PhoneMine-js#1]

**Comment by trevorwb** [comment]
unless it was overwritten, one of my last check in fixed this

**Comment by trevorwb** [comment]
https://github.com/tyler-markvluwer/PhoneMine-js/commit/d6fe1d0a1dcc24a378efde6efe27c8fad4c45514

**Comment by tyler-markvluwer** [comment]
Yeah I forgot to pull when I made that issue haha. I pulled and it's all
good now.

Also, is the motion sensing alarm working right now? I wanna make sure I
don't break if it is

**Comment by trevorwb** [comment]
Yea, motion sensing was working.

**Comment by tyler-markvluwer** [comment]
okay yeah all looks good. I broke it temporarily, but it's working again.
Also, I'm going through the files and standardizing naming conventions and
style and such. Just a heads up. If you make any change in the next half
hour or so they may cause merge conflicts.

On Sun, Mar 1, 2015 at 1:38 PM, trevorwb <notifications@github.com> wrote:

> Yea, motion sensing was working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tyler-markvluwer/PhoneMine-js/issues/1#issuecomment-76623096>
> .
>



-- 
Tyler Markvluwer
B.S.E Computer Science
University of Michigan class of 2015, Ann Arbor, MI
tylermar@umich.edu

**Comment by trevorwb** [comment]
i'll hold off until your next push.

if ya want to try and remove all the unused coffee files from the initial push, that would be good to clean up

**Comment by tyler-markvluwer** [comment]
I cleaned up most of the files, but left some that I might want to
reference later. I've also been trying to get rid of the initial beep, but
am having a hard time with it.

On Sun, Mar 1, 2015 at 2:04 PM, trevorwb <notifications@github.com> wrote:

> i'll hold off until your next push.
>
> if ya want to try and remove all the unused coffee files from the initial
> push, that would be good to clean up
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tyler-markvluwer/PhoneMine-js/issues/1#issuecomment-76624383>
> .
>



-- 
Tyler Markvluwer
B.S.E Computer Science
University of Michigan class of 2015, Ann Arbor, MI
tylermar@umich.edu

**Comment by tyler-markvluwer** [comment]
Yeah I just spent a good couple hours on it, and I couldn't figure it out.
I think I gotta take a break from it for a bit

On Sun, Mar 1, 2015 at 2:28 PM, Tyler Markvluwer <tylermar@umich.edu> wrote:

> I cleaned up most of the files, but left some that I might want to
> reference later. I've also been trying to get rid of the initial beep, but
> am having a hard time with it.
>
> On Sun, Mar 1, 2015 at 2:04 PM, trevorwb <notifications@github.com> wrote:
>
>> i'll hold off until your next push.
>>
>> if ya want to try and remove all the unused coffee files from the initial
>> push, that would be good to clean up
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tyler-markvluwer/PhoneMine-js/issues/1#issuecomment-76624383>
>> .
>>
>
>
>
> --
> Tyler Markvluwer
> B.S.E Computer Science
> University of Michigan class of 2015, Ann Arbor, MI
> tylermar@umich.edu
>
>


-- 
Tyler Markvluwer
B.S.E Computer Science
University of Michigan class of 2015, Ann Arbor, MI
tylermar@umich.edu
