### ISSUE TITLE
Attach image/canvas to email.

### ISSUE THREAD

**Issue by trevorwb** [tyler-markvluwer/PhoneMine-js#11]
App is taking picture, but now we need to get picture back to the user.

Either figure out the email attachment we have been trying OR

I think the Imgur API solution I proposed would be a good route.

**Comment by tyler-markvluwer** [comment]
I got the Imgur API working after a some wrestling with it. Sendgrid won't let me attach the imgur photo as an attachment, but I can include the URL in the email body, so that's some progress.
