### ISSUE TITLE
automatic picture taking is impossible....

### ISSUE THREAD

**Issue by tyler-markvluwer** [tyler-markvluwer/PhoneMine-js#8]
I don't know how much you guys have looked into it, but I'm not having any luck with the automatic picture taking. If you have a chance to look at what code is in camTest before tomorrow that'd be good.

**Comment by trevorwb** [comment]
I've been working with this all day.

Can you guys even get navigator.camera.getPicturenavigator.camera.getPicture() to load the camera on our app? I'm not sure why I can't get that to bring up the camera, even to take a manual photo.

But I have a demo working for the web, where I start a hidden video when the keypad gets brought up, then take a pic/snanshot of the video stream when the alarm goes off.

This uses html webkitGetUserMedia and has to ask for permissions when the webpage loads.

I have not been able to get this work on my phone, it might have to do with the browser; still want to try a few things.

But even if we can't get this html method to work on the phone, maybe we could use a similar idea, with the video to snapshot implemented with cordova plugins or something.

**Comment by trevorwb** [comment]
Ok, looks like switching to cordova crosswalk could let my getusermedia solution work on android

**Comment by trevorwb** [comment]
Closing this. My html5 video/canvas solution works. Using Crosswalk to allow Chrome WebViews allows this to work on the phone as well.
